### ISSUE TITLE
Cannot change version number

### ISSUE THREAD

**Issue by gezakukoda** [msintuneappsdk/intune-app-wrapping-tool-mac#25]
I am not sure if this is an issue or I am doing something wrong. I am trying to change the package version of the output file but doesn't matter what I do Intune always says:

> Update this app by selecting a newer line of business app package. The version of your existing package is [1.0], and the one you selected has version [1.0]

The command I use is the following:
`sudo ./IntuneAppUtil -c nameoftheapp.pkg -o ~/Downloads/ -n 2.0`

**Comment by MietekW** [comment]
I think you are trying to replace an exsisting app within Intune correct?
Maybe if you run the command below on both the packages (intunemac), provides more information.

IntuneAppUtil -r <filename.intunemac> [-v]
This will extract the detected parameters and version for the created .intunemac file.

**Comment by MietekW** [comment]
Did a test, it seems you need to use both parameters

sudo ./IntuneAppUtil -c nameoftheapp.pkg -o ~/Downloads/ -i 2 -n 3

IntuneAppUtil -r <filename.intunemac> -v
will show: Bundleid="2" Buildnumber "3"

Also do not overwrite the file it gave me mixed results, when running the -r -v

**Comment by gezakukoda** [comment]
Thanks for your answer. It works if I use both parameters.
