### ISSUE TITLE
IntuneAppUtil can't deploy PKGs containing multiple files/folders

### ISSUE THREAD

**Issue by madara506** [msintuneappsdk/intune-app-wrapping-tool-mac#36]
Hi there!

Is it expected behavior that IntuneAppUtil can only delpoys .app to the /Applications folder and that it's not possible for example to deploy something like [**Octory**](https://gitlab.com/amarisgroup/octory-config) which is an application that goes in /Library/Application Support/ requiring configuration files to work?

**Comment by aaronparker** [comment]
This is correct; however, an update is coming to fix this: https://twitter.com/claus_jespersen/status/1369039038401888269?s=20

**Comment by madara506** [comment]
Perfect thanks a lot Aaron!
